### ISSUE TITLE
studio.status.im 'projects' button incorrectly links to 'community'

### ISSUE THREAD

**Issue by Shrinks99** [status-im/status.im#106]
When you click the `projects` button on the nav bar of [studio.status.im](https://studio.status.im/), the website opens the community tab instead of the projects tab.  See [status.im](https://status.im/) for expected behaviour.

**Comment by samthomson** [comment]
should this issue be moved to the https://github.com/status-im/studio.status.im repo ?

**Comment by samthomson** [comment]
Assign this to me and I'll take care of it :)

**Comment by andytudhope** [comment]
Hi @samthomson - so "taking care" of this is a little more involved than you might think. We moved across to `sass` on the main page and shifted the JS about a bit, so I need to replicate that on both `studio` and `incubate` in order to get the menu drop down working correctly. Might just be easiest if I take care of it at some stage this week, but thanks for the offer ❤️

**Comment by samthomson** [comment]
Whatever you think's best :+1: I had thought I'd replicate what's on status.im, but did think maybe that could be refactored into something shared across sites. I'll leave it to you guys and stay out of the way :)

**Comment by samthomson** [comment]
No worries on the late reply, sure DevCon was worth it :)
Sure I'd be happy to help out. Haven't solved a bounty before so would be interested to see how that flow runs. Go for it.


As for ideas.

NPM package: create an npm package to be included in each repo which spits out the correct menu/html/js. Does the job, fits with the existing package structure. A package that generates hard coded html seems bad, to me passing a menu structure that the package renders as html seems more 'proper' although that would mean reducing but not removing duplicity (the menu structure) across static site repos, but maybe following strict MVCesque patterns isn't necessary.

Submodules: make a seperate repo just for the menu, which would then be included with the git submodule pattern in the respective static website repo. Cloning any of the website repos would update the included submodule repo too.

Both ideas involve mixing view-templates/partials with hard coded data but the site already does that anyway so maybe not a big deal.
Git submodules seems complicated, but should work nicely and avoids having to create an npm module and then update it everytime a menu update is needed.

Git subtrees is another solution (not too different to submodules). Also a seperate git repo could be made for the menu and symlinked in to each static site. Although unnecessarily hacky not to mention an annoying step for new contributors to set up.

I'm happy to look into any/all of the above and see what works and submit some PRs to evaluate and start a dialog around. At this stage I think submodules/subtrees seem a good idea. I'll look more at hexo too and see if there is an existing simple way to solve the problem.

**Comment by andytudhope** [comment]
Hi @samthomson let's try with the git submodules pattern first I think, will create a bounty here for you shortly to get it done. It may be worth waiting a day or 2 for this issue and fix to be solved and merged:  #120 as we may be able to get rid of the gulp file here and make sure that the process is exactly the same for each site without too much extra work...

**Comment by samthomson** [comment]
Sounds good, I've subscribed to #120 to see when it's wrapped up,.

**Comment by andytudhope** [comment]
Hey @samthomson I have been foiled by a failure in Gitcoin for the moment, but this does not mean you cannot begin work here. Please see #126 for details.

We need to make sure that nimbus.status.im; studio.status.im and incubate.status.im all use the same format so that it's easy to contribute across the board. 126 links to issues I have created in each for moving the styles across, cleaning up a bit and removing unnecessary JS etc. Each of those issues will be for 120 DAI and the submodules issue will be 240 DAI, for a total of 600 DAI (i.e. 600 USD) for all the work. Does that sound like a fair deal to you? 

Please comment in 126 either way (i.e. "It is not fair" or "I am starting") and I will get those bounties up and running as soon as Gitcoin is on its feet again.
