### ISSUE TITLE
Blog Not updating with latest content

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#352]
Most recent blog post "Token Economics Research" is not appearing in the featured #1 spot on the blog NOR on the homepage in the "News" section on the homepage

https://our.status.im/token-economics-ens-usernames/

<img width="1270" alt="Screen Shot 2019-06-03 at 1 17 59 PM" src="https://user-images.githubusercontent.com/33129508/58820981-0a289880-8602-11e9-844b-c52dfa09b4c6.png">
<img width="1280" alt="Screen Shot 2019-06-03 at 1 17 58 PM" src="https://user-images.githubusercontent.com/33129508/58820982-0a289880-8602-11e9-8b33-787e9a53efbb.png">

**Comment by NistorCristian** [comment]
@j-zerah That's because it's not the most recent post. The most recent post published is [Version 0.13.0 - Custom ERC20 Token Support](https://our.status.im/version-0-13-0-custom-erc20-token-support/).

This post is published on 05/28/2019 at 13:15
The post that you want to be first is published on 05/28/2019 at 10:24

Do you want me to change the hour and make that the latest post published?

**Comment by j-zerah** [comment]
@NistorCristian - you are correct. I completely forgot this post was accidentally published a few weeks ago on 5/28.

Yes - please make this the most recent post.

**Comment by NistorCristian** [comment]
@j-zerah Done
