### ISSUE TITLE
[Homepage] Last post from our.status.im doesn't load due to CORS

### ISSUE THREAD

**Issue by NistorCristian** [status-im/status.im#410]
Hi,

There is an issue on homepage. Below the title "Private, Secure Communication" on homepage there should be a news link in there that gets the last post published on https://our.status.im/.

The problem is that because of CORS the post can't be fetched. Here is the error:

`Access to XMLHttpRequest at 'https://our.status.im/ghost/api/v2/content/posts/?key=10e7f8c1f793d2945ea1177076&limit=1&fields=title,url' from origin 'https://status.im' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, https://status.im', but only one is allowed.`

If I remember @jakubgs fixed this issue but in the meantime you activated CloudFlare if I remember correctly that might be related to this issue. Just a guess here.

**Comment by jakubgs** [comment]
Thanks, shouldn't be hard to fix.

**Comment by jakubgs** [comment]
Oh yeah, I can see the issue:
```
 $ curl -s 'https://our.status.im/ghost/api/v2/content/posts/?key=10e7f8c1f793d2945ea1177076&limit=1&fields=title,url' -i -H 'origin: https://status.im' | grep origin    
access-control-allow-origin: *
access-control-allow-origin: https://status.im
```
Both Ghost and the Nginx proxy for Ghost set the `access-control-allow-origin` header which fucks with the browsers a bit.

**Comment by jakubgs** [comment]
And the current configuration adds it without check if there is already one:
https://github.com/status-im/infra-misc/blob/a3043b686a7d459ef5b05fc4a46612ff5b2dc578/ansible/roles/ghost/templates/cors-setup.conf.j2#L2-L7
What I could use is the [proxy_set_header](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) option to clear the header first.

**Comment by jakubgs** [comment]
Since I can't easily remove the `access-control-allow-origin` header myself in Nginx I'm just going to drop the CORS adding on the proxy. My guess is it was necessary for the older Ghost version, and the new one just adds it by itself, so we get two headers.

Fix: https://github.com/status-im/infra-misc/commit/282ea232cbb96666ee317b235bb4157cc431a93e

![fixed_news_link](https://user-images.githubusercontent.com/2212681/66156613-486eac80-e622-11e9-90c4-fb6472b334d9.png)
